language: csharp
solution: msconfig.sln
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Automated build from Travis CI. Build number #$TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/TCDG/msconfig --tags
  - ls -R
  - export JAR_FILE=$(ls build/libs/Diskurd-*.jar)
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$TAGPERM"
  file_glob: true
  file: "${JAR_FILE}"
  on:
    tags: false
    branch: master
branches:
  except:
    - /^*-v[0-9]/
notifications:
  email:
    on_success: change
    on_failure: change
